AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        GetData:
          Type: Api
          Properties:
            Path: '/'
            Method: Get
            RestApiId:
              Ref: ApiGatewayApi
        PostData:
          Type: Api
          Properties:
            Path: '/'
            Method: Post
            RestApiId:
              Ref: ApiGatewayApi

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: 'api'

  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: my-api-key
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: 'api'

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      Cors:
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: true
